pipeline {

    agent {
        dockerfile {
            dir 'automation'
            reuseNode true
        }
    }

    stages {
        stage('Clippy') {
            steps {
                sh 'cargo clippy'
            }
        }
        stage('Rustfmt') {
            steps {
                sh 'cargo fmt'
            }
        }
        stage('Test') {
            steps {
                sh 'cargo test'
            }
        }
        stage('Check') {
            steps {
                sh 'cargo check'
            }
        }
        stage('Check Cross') {
            steps {
                sh 'cargo check --target thumbv7em-none-eabihf --no-default-features'
            }
        }
    }
}
